# Generated by Django 4.1.3 on 2022-11-14 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_person_play_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='player',
        ),
        migrations.RemoveField(
            model_name='play',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='play',
            name='team',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Play',
        ),
    ]
